/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'PascalMacBookPro' at '1/24/17 5:02 PM' with Gradle 2.14.1
 *
 * @author PascalMacBookPro, @date 1/24/17 5:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
